name: lightning
channels:
- conda-forge
- defaults
dependencies:
- pandas
- numpy
- jupyter
- matplotlib
- cartopy
- seaborn
- xarray
- pytables
- geopy
- pip:
  - windrose
  - python-dotenv
  - git+git://github.com/jsignell/point-process.git
